### ISSUE TITLE
Problem with compiling

### ISSUE THREAD

**Issue by alexforges** [Dewott2501/Mario-Madness#17]
i tried compilate the Mario Madness v2 and i have no idea what the problem

![image](https://github.com/Dewott2501/Mario-Madness/assets/98671791/3e4d0b69-3b08-416d-9954-4ca4b0adbd39)

here list my haxelib
![image](https://github.com/Dewott2501/Mario-Madness/assets/98671791/85bc99e1-8194-4aa7-ab5e-09362f6b1ed7)

**Comment by Dewott2501** [comment]
try installing lime 8.0.2

**Comment by Maz-github** [comment]
i just get 


C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/sound/FlxSound.hx:752: characters 17-25 : flash.media.SoundChannel has no field __source
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/sound/FlxSound.hx:753: characters 14-22 : flash.media.SoundChannel has no field __source
source/PlayState.hx:12161: characters 32-59 : Warning : This pattern is unused
source/Transparency.hx:25: lines 25-26 : Warning : Extern non-inline function may not have an expression
source/Transparency.hx:29: lines 29-30 : Warning : Extern non-inline function may not have an expression
source/Transparency.hx:33: lines 33-34 : Warning : Extern non-inline function may not have an expression
source/Transparency.hx:37: lines 37-38 : Warning : Extern non-inline function may not have an expression
source/Transparency.hx:41: lines 41-42 : Warning : Extern non-inline function may not have an expression
source/PlayState.hx:16723: lines 16723-16731 : Warning : This case is unused

lmao

**Comment by Maz-github** [comment]
haxelib install openfl 9.2.0 

worked for me

**Comment by moxie-coder** [comment]
also, make sure you're using haxe 4.2.5

**Comment by alexforges** [comment]
it's helped thx verry guys ❤️
