### ISSUE TITLE
Story mode broken when building the source code on mac.

### ISSUE THREAD

**Issue by BrutarTheHero** [Dewott2501/Mario-Madness#2]
So i've followed all of the instructions on how to build this mod's Source Code on mac, and everything seemed to work fine, While playtesting however, Story Mode's cutscenes were being skipped, When i finished goldenland, the game just froze at a blackscreen, Not allowing me to gain access to the warp zone's songs.
<img width="1281" alt="Screenshot 2022-02-27 at 12 56 23" src="https://user-images.githubusercontent.com/44065559/155881454-16152171-2378-4bd8-8587-73346d541f43.png">
(The aftermath of beating goldenland, just an example of what it would look like.)

Has anyone else encountered this issue, and if that happens to be the case, Is there a way to fix it?

**Comment by beeanie** [comment]
yes 
the reason why its acting like that is because its using mp4 video for it

**Comment by BrutarTheHero** [comment]
Ooooh, alright.
