### ISSUE TITLE
Won't download.

### ISSUE THREAD

**Issue by FlamingoFlim** [Dewott2501/Mario-Madness#25]
No matter how much times i try to download the source from here it just ends up with errors, It's actually really infuriating at how much times something like this has happened.
![image](https://github.com/Dewott2501/Mario-Madness/assets/73727131/9f040273-3c89-4b67-8050-8cabfcd09491)

**Comment by moxie-coder** [comment]
it’s an issue with your WiFi, also use git or GitHub desktop instead of directly downloading the zip
