### ISSUE TITLE
Problems building AND testing MMV2.

### ISSUE THREAD

**Issue by FlamingoFlim** [Dewott2501/Mario-Madness#26]
![image](https://github.com/Dewott2501/Mario-Madness/assets/73727131/1de128db-a5fe-455a-9880-7b1f3c002200)
I don't know why this happens. anybody here got some components i need for this to work, or anything i need in the code to be wiped and or changed?

**Comment by moxie-coder** [comment]
make sure to run`complations_preset.bat` and use haxe 4.2.5

**Comment by FlamingoFlim** [comment]
I see
