### ISSUE TITLE
Unable to build on linux

### ISSUE THREAD

**Issue by yaboytabby** [Dewott2501/Mario-Madness#27]
not quite sure if this is a haxe or MM issue, but it never happened when building plain old psych engine. When attempting to 'lime test linux' or 'lime build linux' it throws an error, not being able to find hxcodec. problem is, i have hx codec installed.

**Comment by moxie-coder** [comment]
it’s an bug with haxelib, remove and reinstall hxCodec with `haxelib install hxCodec 2.5.1`

**Comment by Noobz4Life** [comment]
In project.xml, replace "hxcodec" on line 66 with "hxCodec", since file paths are case sensitive on Linux

**Comment by Ant643** [comment]
worked 4 me, thanks

**Comment by basil-squared** [comment]
thanx
