### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by NickIdk1235** [Dewott2501/Mario-Madness#28]
![image](https://github.com/Dewott2501/Mario-Madness/assets/97841607/7bed4a64-bdbd-4a52-aab1-c9b03049a970)

**Comment by Dewott2501** [comment]
use the [complations_preset.bat](https://github.com/Dewott2501/Mario-Madness/blob/main/complations_preset.bat) file in the folder root

**Comment by NickIdk1235** [comment]
Thanks
