### ISSUE TITLE
make the flute scene an animation instead of a mp4

### ISSUE THREAD

**Issue by ghost** [Dewott2501/Mario-Madness#3]
we mac porters want to port this mod but the flute scene has mp4 coding so i wondering if you can please make it a animation .

**Comment by ZHyproX** [comment]
YOU MAC PORTER ANNOYAİNG AS ALWAYS

**Comment by McJonnycat** [comment]
what did we do were just trying to do our job

**Comment by McJonnycat** [comment]
cause the people asked for it
