### ISSUE TITLE
problem with source code compiling

### ISSUE THREAD

**Issue by Komorie6** [Dewott2501/Mario-Madness#42]
source/PlayState.hx:12161: characters 32-59 : Warning : (WUnusedPattern) This pattern is unused
source/Transparency.hx:25: lines 25-26 : Warning : (WExternWithExpr) Extern non-inline function may not have an expression
source/Transparency.hx:29: lines 29-30 : Warning : (WExternWithExpr) Extern non-inline function may not have an expression
source/Transparency.hx:33: lines 33-34 : Warning : (WExternWithExpr) Extern non-inline function may not have an expression
source/Transparency.hx:37: lines 37-38 : Warning : (WExternWithExpr) Extern non-inline function may not have an expression
source/Transparency.hx:41: lines 41-42 : Warning : (WExternWithExpr) Extern non-inline function may not have an expression
source/PlayState.hx:16723: lines 16723-16731 : Warning : (WUnusedPattern) This case is unused
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/FlxG.hx:3: characters 8-17 : You cannot access the flash package while in a macro (for flash.Lib)
source/openfl/display/OptimizedBitmapData.hx:3: characters 8-19 : ... referenced here
source/openfl/utils/Assets.hx:5: characters 8-42 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
source/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

**Comment by Komorie6** [comment]
nvm i figured it out myself

**Comment by IcyeeCube** [comment]
What did you do to fix it?

> nvm i figured it out myself

**Comment by sopitaau** [comment]
HOW DO U FIX IT???
